title: Jialei He's Homepage
page-top-title: Jialei He
top-section-bg-text: Bridge Engineering & Artificial Intelligence
home-subtitle: Jialei He&ensp;|&ensp;何佳磊
copyright-text: '&copy; Jialei He 2024-2025. All Rights Reserved.'
